import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "@/components/student-dashboard/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="w-full flex flex-col md:flex-row gap-0">
          <div className="lg:w-60 md:w-full">
            <Sidebar/>
          </div>
          <div className="flex-1 lg:w-2/3 md:w-full ">{children}</div>
        </div>
      </body>
    </html>
  );
}
